/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb.util;

import Lukavronb.language.Lukavronb.Lukavronb_valuation;
import Lukavronb.language.Lukavronb.Lukavronb_formula;

public interface LukavronbExpressionGenerator{

    Lukavronb_valuation valuation();

    Lukavronb_formula formula();

}
