/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavron.language.Lukavron;

import java.util.Set;
import mettel.core.tableau.MettelReplacement;

public interface LukavronReplacement extends MettelReplacement{

    Lukavron_valuation get_valuation(Lukavron_valuation e);

    Set<Lukavron_valuation> valuationKeys();

    boolean append(Lukavron_valuation e0, Lukavron_valuation e1);

    Lukavron_formula get_formula(Lukavron_formula e);

    Set<Lukavron_formula> formulaKeys();

    boolean append(Lukavron_formula e0, Lukavron_formula e1);

    boolean append(LukavronReplacement r);

}
