/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavron.language.Lukavron;

import java.util.Map;
import java.util.TreeMap;

public class LukavronDefaultObjectFactory implements LukavronObjectFactory{

    private Map<LukavronSubstitution, LukavronSubstitution> subs = new TreeMap<LukavronSubstitution, LukavronSubstitution>();

    public LukavronSubstitution getSubstitution(LukavronSubstitution s){
        final LukavronSubstitution old = subs.get(s);
        if(old == null){ 
            subs.put(s,s);
            return s;
        }else{ return old; }
    }

    private Map<LukavronReplacement, LukavronReplacement> reps = new TreeMap<LukavronReplacement, LukavronReplacement>();

    public LukavronReplacement getReplacement(LukavronReplacement r){
        final LukavronReplacement old = reps.get(r);
        if(old == null){ 
            reps.put(r,r);
            return r;
        }else{ return old; }
    }

    public Lukavron_valuation create_true_valuation(Lukavron_formula e0){
        final Lukavron_true_valuation e = new Lukavron_true_valuation(e0, this);
        final Lukavron_valuation old = valuations.get(e);
        if(old == null){ 
            valuations.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavron_valuation create_false_valuation(Lukavron_formula e0){
        final Lukavron_false_valuation e = new Lukavron_false_valuation(e0, this);
        final Lukavron_valuation old = valuations.get(e);
        if(old == null){ 
            valuations.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavron_formula create_negation_formula(Lukavron_formula e0){
        final Lukavron_negation_formula e = new Lukavron_negation_formula(e0, this);
        final Lukavron_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavron_formula create_conjunction_formula(Lukavron_formula e0, Lukavron_formula e1){
        final Lukavron_conjunction_formula e = new Lukavron_conjunction_formula(e0, e1, this);
        final Lukavron_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavron_formula create_disjunction_formula(Lukavron_formula e0, Lukavron_formula e1){
        final Lukavron_disjunction_formula e = new Lukavron_disjunction_formula(e0, e1, this);
        final Lukavron_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavron_formula create_implication_formula(Lukavron_formula e0, Lukavron_formula e1){
        final Lukavron_implication_formula e = new Lukavron_implication_formula(e0, e1, this);
        final Lukavron_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    private Map<String, Lukavron_valuationVariable> valuationVariables = new TreeMap<String, Lukavron_valuationVariable>();

    public Lukavron_valuationVariable create_valuationVariable(String name){
        Lukavron_valuationVariable v = valuationVariables.get(name);
        if(v == null){
            v = new Lukavron_valuationVariable(name, this);
            valuationVariables.put(name, v);
        }
        return v;
    }

    private Map<Lukavron_valuation, Lukavron_valuation> valuations = new TreeMap<Lukavron_valuation, Lukavron_valuation>();

    private Map<String, Lukavron_formulaVariable> formulaVariables = new TreeMap<String, Lukavron_formulaVariable>();

    public Lukavron_formulaVariable create_formulaVariable(String name){
        Lukavron_formulaVariable v = formulaVariables.get(name);
        if(v == null){
            v = new Lukavron_formulaVariable(name, this);
            formulaVariables.put(name, v);
        }
        return v;
    }

    private Map<Lukavron_formula, Lukavron_formula> formulas = new TreeMap<Lukavron_formula, Lukavron_formula>();

}
