/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavron.language.Lukavron;

abstract class LukavronAbstractVariable extends LukavronAbstractExpression implements LukavronVariable{

    String name = null;

    public String name(){
        return name;
    }

    public LukavronAbstractVariable(String name, LukavronObjectFactory factory){
        super(factory);
        this.name = name;
    }

    public String toString(){
        return name;
    }
    int priority(){
        return -1;
    }
}
