/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavron.language.Lukavron;

import mettel.core.tableau.MettelExpression;
public interface LukavronExpression extends MettelExpression{

    int id();
    LukavronObjectFactory factory();
    LukavronExpression substitute(LukavronSubstitution s);
    LukavronExpression rewrite(LukavronReplacement r);
    LukavronSubstitution match(LukavronExpression e);

    boolean match(LukavronExpression e, LukavronSubstitution s);
}
