/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavron.language.Lukavron;

public interface Lukavron_formula extends LukavronExpression{

    final int SORTID = 2;
}
