/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavron.language.Lukavron;

import java.util.Map;
import mettel.core.tableau.MettelSubstitution;
public interface LukavronSubstitution extends MettelSubstitution{

    Lukavron_valuation get_valuation(Lukavron_valuationVariable e);

    Map<Lukavron_valuationVariable, Lukavron_valuation> valuationMap();

    boolean append(Lukavron_valuationVariable e0, Lukavron_valuation e1);

    Lukavron_formula get_formula(Lukavron_formulaVariable e);

    Map<Lukavron_formulaVariable, Lukavron_formula> formulaMap();

    boolean append(Lukavron_formulaVariable e0, Lukavron_formula e1);

}
