/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavron.language.Lukavron;

import java.util.Comparator;

public class LukavronIDComparator implements Comparator<LukavronAbstractExpression>{

    public int compare(LukavronAbstractExpression e0, LukavronAbstractExpression e1){
        return e0.id() - e1.id();
    }

}
