/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavron.language.Lukavron.util;

import Lukavron.language.Lukavron.Lukavron_valuation;
import Lukavron.language.Lukavron.Lukavron_formula;

public interface LukavronExpressionGenerator{

    Lukavron_valuation valuation();

    Lukavron_formula formula();

}
