/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukasiewicz.language.Lukasiewicz;

import java.util.Set;
import mettel.core.tableau.MettelReplacement;

public interface LukasiewiczReplacement extends MettelReplacement{

    Lukasiewicz_valuation get_valuation(Lukasiewicz_valuation e);

    Set<Lukasiewicz_valuation> valuationKeys();

    boolean append(Lukasiewicz_valuation e0, Lukasiewicz_valuation e1);

    Lukasiewicz_formula get_formula(Lukasiewicz_formula e);

    Set<Lukasiewicz_formula> formulaKeys();

    boolean append(Lukasiewicz_formula e0, Lukasiewicz_formula e1);

    boolean append(LukasiewiczReplacement r);

}
