/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukasiewicz.language.Lukasiewicz;

import java.util.Map;
import java.util.TreeMap;
import java.util.Map.Entry;
import java.util.Set;
import java.util.TreeSet;

import mettel.core.tableau.MettelSubstitution;
public class LukasiewiczTreeSubstitution implements LukasiewiczSubstitution{

    protected final Map<Lukasiewicz_valuationVariable, Lukasiewicz_valuation> valuationMap = new TreeMap<Lukasiewicz_valuationVariable, Lukasiewicz_valuation>();
    public Lukasiewicz_valuation get_valuation(Lukasiewicz_valuationVariable v){
        return valuationMap.get(v);
    }

    public Map<Lukasiewicz_valuationVariable, Lukasiewicz_valuation> valuationMap(){
        return valuationMap;
    }

    public boolean append(Lukasiewicz_valuationVariable v, Lukasiewicz_valuation e1){
        if(v == null || e1 == null){ return false; }
        final Lukasiewicz_valuation e = valuationMap.get(v);
        if(e == null){
            valuationMap.put(v,e1);
            return true;
        }else{
            return (e.equals(e1));
        }
    }

    protected final Map<Lukasiewicz_formulaVariable, Lukasiewicz_formula> formulaMap = new TreeMap<Lukasiewicz_formulaVariable, Lukasiewicz_formula>();
    public Lukasiewicz_formula get_formula(Lukasiewicz_formulaVariable v){
        return formulaMap.get(v);
    }

    public Map<Lukasiewicz_formulaVariable, Lukasiewicz_formula> formulaMap(){
        return formulaMap;
    }

    public boolean append(Lukasiewicz_formulaVariable v, Lukasiewicz_formula e1){
        if(v == null || e1 == null){ return false; }
        final Lukasiewicz_formula e = formulaMap.get(v);
        if(e == null){
            formulaMap.put(v,e1);
            return true;
        }else{
            return (e.equals(e1));
        }
    }

    public boolean append(LukasiewiczSubstitution s){
        final Map<Lukasiewicz_valuationVariable, Lukasiewicz_valuation> m_valuation = s.valuationMap();
        for(Lukasiewicz_valuationVariable key:m_valuation.keySet()){
            if(!append(key,s.get_valuation(key))){ return false; }
        }
        final Map<Lukasiewicz_formulaVariable, Lukasiewicz_formula> m_formula = s.formulaMap();
        for(Lukasiewicz_formulaVariable key:m_formula.keySet()){
            if(!append(key,s.get_formula(key))){ return false; }
        }
        return true;
    }

    public MettelSubstitution merge(MettelSubstitution s){
        LukasiewiczTreeSubstitution result = new LukasiewiczTreeSubstitution();
        result.append(this);
        if(result.append((LukasiewiczTreeSubstitution)s)){
            return result;
        }else{
            return null;
        }
    }

    private static LukasiewiczTreeSubstitution appendArray(LukasiewiczTreeSubstitution s, MettelSubstitution[] array){
        if(array == null) return null;
        final int SIZE = array.length;
        if(SIZE == 0) return null;
        for(int i = 0; i < SIZE; i++){
            Set<Entry<Lukasiewicz_valuationVariable, Lukasiewicz_valuation>> entry_valuationSet = ((LukasiewiczSubstitution)array[i]).valuationMap().entrySet();
            for(Entry<Lukasiewicz_valuationVariable, Lukasiewicz_valuation> entry:entry_valuationSet){
                if(!s.append(entry.getKey(),entry.getValue())) return null;
            }
            Set<Entry<Lukasiewicz_formulaVariable, Lukasiewicz_formula>> entry_formulaSet = ((LukasiewiczSubstitution)array[i]).formulaMap().entrySet();
            for(Entry<Lukasiewicz_formulaVariable, Lukasiewicz_formula> entry:entry_formulaSet){
                if(!s.append(entry.getKey(),entry.getValue())) return null;
            }
        }
        return s;
    }

    public MettelSubstitution mergeArray(MettelSubstitution[] array){
        return appendArray(new LukasiewiczTreeSubstitution(),array);
    }

    public MettelSubstitution merge(MettelSubstitution[] array){
        LukasiewiczTreeSubstitution s = new LukasiewiczTreeSubstitution();
        s.valuationMap().putAll(valuationMap);
        s.formulaMap().putAll(formulaMap);
        return appendArray(s,array);
    }

    public int compareTo(MettelSubstitution s){
        if(s == this){ return 0; }
        final Set<Lukasiewicz_valuationVariable> keys_valuation0 = valuationMap.keySet();
        final Set<Lukasiewicz_valuationVariable> keys_valuation1 = ((LukasiewiczSubstitution)s).valuationMap().keySet();
        final TreeSet<Lukasiewicz_valuationVariable> keys_valuation = new TreeSet<Lukasiewicz_valuationVariable>(keys_valuation0);
        keys_valuation.addAll(keys_valuation1);
        for(Lukasiewicz_valuationVariable key:keys_valuation){
            if(!keys_valuation0.contains(key)){
                return 1;
            }else{
                if(!keys_valuation1.contains(key)){
                    return -1;
                }else{
                    final Lukasiewicz_valuation v0 = valuationMap.get(key);
                    final Lukasiewicz_valuation v1 = ((LukasiewiczSubstitution)s).get_valuation(key);
                    final int result = v0.compareTo(v1);
                    if(result != 0){ return result; }
                }
            }
        }
        final Set<Lukasiewicz_formulaVariable> keys_formula0 = formulaMap.keySet();
        final Set<Lukasiewicz_formulaVariable> keys_formula1 = ((LukasiewiczSubstitution)s).formulaMap().keySet();
        final TreeSet<Lukasiewicz_formulaVariable> keys_formula = new TreeSet<Lukasiewicz_formulaVariable>(keys_formula0);
        keys_formula.addAll(keys_formula1);
        for(Lukasiewicz_formulaVariable key:keys_formula){
            if(!keys_formula0.contains(key)){
                return 1;
            }else{
                if(!keys_formula1.contains(key)){
                    return -1;
                }else{
                    final Lukasiewicz_formula v0 = formulaMap.get(key);
                    final Lukasiewicz_formula v1 = ((LukasiewiczSubstitution)s).get_formula(key);
                    final int result = v0.compareTo(v1);
                    if(result != 0){ return result; }
                }
            }
        }
        return 0;
    }

    private int hashCode = 0;
    public int hashCode(){
        hashCode = 1;
        hashCode = 31*hashCode + valuationMap.hashCode();
        hashCode = 31*hashCode + formulaMap.hashCode();
        return hashCode;
    }

    public boolean equals(Object o){
        if(o == this){ return true; }
        if(!(o instanceof LukasiewiczSubstitution)){ return false; }
        final LukasiewiczSubstitution s = (LukasiewiczSubstitution)o;
        return valuationMap.equals(s.valuationMap()) && formulaMap.equals(s.formulaMap());
    }

    public String toString(){
        StringBuilder b = new StringBuilder();
        b.append("$[");
        boolean notFirst = false;
        Set<Entry<Lukasiewicz_valuationVariable, Lukasiewicz_valuation>> valuationEntrySet = valuationMap.entrySet();
        for(Entry<Lukasiewicz_valuationVariable, Lukasiewicz_valuation> entry:valuationEntrySet){
            if(notFirst){
                b.append(", ");
            }else{
                notFirst = true;
            }
            b.append(entry.getKey());
            b.append('/');
            b.append(entry.getValue());
        }
        Set<Entry<Lukasiewicz_formulaVariable, Lukasiewicz_formula>> formulaEntrySet = formulaMap.entrySet();
        for(Entry<Lukasiewicz_formulaVariable, Lukasiewicz_formula> entry:formulaEntrySet){
            if(notFirst){
                b.append(", ");
            }else{
                notFirst = true;
            }
            b.append(entry.getKey());
            b.append('/');
            b.append(entry.getValue());
        }
        b.append(']');
        return b.toString();
    }

}
