/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukasiewicz.language.Lukasiewicz;

import java.util.Comparator;

import mettel.core.tableau.MettelExpression;

public class Lukasiewicz_false_valuation extends LukasiewiczAbstractExpression implements Lukasiewicz_valuation{

    static final int PRIORITY = 3;
    private final int LENGTH;
    protected Lukasiewicz_formula e0 = null;

    public Lukasiewicz_false_valuation(Lukasiewicz_formula e0, LukasiewiczObjectFactory f){
        super(f);
        int l = 1;
        this.e0 = e0;
        l += e0.length();
        LENGTH = l;
    }

    int sortId(){ return SORTID; }

    int priority(){ return PRIORITY; }

    public int length(){ return LENGTH; }

    public LukasiewiczSubstitution match(LukasiewiczExpression e){
        LukasiewiczSubstitution s = new LukasiewiczTreeSubstitution();
        if(match(e,s)){
            return factory.getSubstitution(s);
        }else{ return null; }
    }

    public boolean match(LukasiewiczExpression e, LukasiewiczSubstitution s){
        if(!(e instanceof Lukasiewicz_false_valuation)){ return false;}
        final Lukasiewicz_false_valuation ee = (Lukasiewicz_false_valuation)e;
        return e0.match(ee.e0, s);
    }

    public LukasiewiczExpression substitute(LukasiewiczSubstitution s){
        return factory.create_false_valuation((Lukasiewicz_formula)e0.substitute(s));
    }

    public LukasiewiczExpression rewrite(LukasiewiczReplacement s){
        LukasiewiczExpression e = s.get_valuation(this);
        if(e != null){ return e; }
        final Lukasiewicz_valuation ee = factory.create_false_valuation((Lukasiewicz_formula)e0.rewrite(s));
        e = s.get_valuation(ee);
        if(e == null){ return ee; }else{ return e; }
    }

    private int hashCode = 0;
    public int hashCode(){
        if(hashCode == 0){
            hashCode = 31*SORTID + PRIORITY;
            hashCode = 31*hashCode + e0.hashCode();
        }
        return hashCode;
    }

    public boolean equals(Object o){
        if(o == this){ return true; }
        if(!(o instanceof Lukasiewicz_false_valuation)){ return false; }
        Lukasiewicz_false_valuation e = (Lukasiewicz_false_valuation) o;
        return (e0.equals(e.e0));
    }

    int compareArgumentsTo(LukasiewiczAbstractExpression e, Comparator<LukasiewiczAbstractExpression> c){
        int result = 0;
        result = c.compare((LukasiewiczAbstractExpression)e0, e);
        if(result >= 0){ return 1; }
        return 0;
    }
    int compareArguments(LukasiewiczAbstractExpression e, Comparator<LukasiewiczAbstractExpression> c){
        final Lukasiewicz_false_valuation ee = (Lukasiewicz_false_valuation)e;
        int result = 0;
        result = c.compare((LukasiewiczAbstractExpression)e0, (LukasiewiczAbstractExpression)ee.e0);
        if(result != 0){ return result; }
        return 0;
    }
    public int compareTo(MettelExpression e){
        if(e == this){ return 0; }
        if(!(e instanceof Lukasiewicz_valuation)){ return SORTID - ((LukasiewiczAbstractExpression)e).sortId(); }
        if(e instanceof Lukasiewicz_valuationVariable){ return 1; }
        if(!(e instanceof Lukasiewicz_false_valuation)){ return PRIORITY - ((LukasiewiczAbstractExpression)e).priority(); }
        Lukasiewicz_false_valuation ee = (Lukasiewicz_false_valuation) e;
        int result = 0;
        result = e0.compareTo(ee.e0);
        if(result != 0){ return result; }
        return 0;
    }


    private String str = null;
    public String toString(){
        if(str == null){
            StringBuilder b = new StringBuilder();
            b.append('(');
            b.append(' ');
            b.append('F');
            b.append(' ');
            b.append(e0);
            b.append(' ');
            b.append(')');
            str = b.toString();
        }
        return str;
    }
}
