/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukasiewicz.language.Lukasiewicz;

import mettel.core.tableau.MettelTableauObjectFactory;
import mettel.core.tableau.MettelReplacement;

public class LukasiewiczTableauObjectFactory implements MettelTableauObjectFactory{

    public MettelReplacement createReplacement(){
        return new LukasiewiczTreeReplacement();
    }

}
