/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukasiewicz.language.Lukasiewicz;

import java.util.Comparator;

public class LukasiewiczIDComparator implements Comparator<LukasiewiczAbstractExpression>{

    public int compare(LukasiewiczAbstractExpression e0, LukasiewiczAbstractExpression e1){
        return e0.id() - e1.id();
    }

}
