/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukasiewicz.language.Lukasiewicz;

import java.util.Map;
import java.util.TreeMap;

public class LukasiewiczDefaultObjectFactory implements LukasiewiczObjectFactory{

    private Map<LukasiewiczSubstitution, LukasiewiczSubstitution> subs = new TreeMap<LukasiewiczSubstitution, LukasiewiczSubstitution>();

    public LukasiewiczSubstitution getSubstitution(LukasiewiczSubstitution s){
        final LukasiewiczSubstitution old = subs.get(s);
        if(old == null){ 
            subs.put(s,s);
            return s;
        }else{ return old; }
    }

    private Map<LukasiewiczReplacement, LukasiewiczReplacement> reps = new TreeMap<LukasiewiczReplacement, LukasiewiczReplacement>();

    public LukasiewiczReplacement getReplacement(LukasiewiczReplacement r){
        final LukasiewiczReplacement old = reps.get(r);
        if(old == null){ 
            reps.put(r,r);
            return r;
        }else{ return old; }
    }

    public Lukasiewicz_valuation create_true_valuation(Lukasiewicz_formula e0){
        final Lukasiewicz_true_valuation e = new Lukasiewicz_true_valuation(e0, this);
        final Lukasiewicz_valuation old = valuations.get(e);
        if(old == null){ 
            valuations.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukasiewicz_valuation create_unknown_valuation(Lukasiewicz_formula e0){
        final Lukasiewicz_unknown_valuation e = new Lukasiewicz_unknown_valuation(e0, this);
        final Lukasiewicz_valuation old = valuations.get(e);
        if(old == null){ 
            valuations.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukasiewicz_valuation create_false_valuation(Lukasiewicz_formula e0){
        final Lukasiewicz_false_valuation e = new Lukasiewicz_false_valuation(e0, this);
        final Lukasiewicz_valuation old = valuations.get(e);
        if(old == null){ 
            valuations.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukasiewicz_formula create_negation_formula(Lukasiewicz_formula e0){
        final Lukasiewicz_negation_formula e = new Lukasiewicz_negation_formula(e0, this);
        final Lukasiewicz_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukasiewicz_formula create_conjunction_formula(Lukasiewicz_formula e0, Lukasiewicz_formula e1){
        final Lukasiewicz_conjunction_formula e = new Lukasiewicz_conjunction_formula(e0, e1, this);
        final Lukasiewicz_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukasiewicz_formula create_disjunction_formula(Lukasiewicz_formula e0, Lukasiewicz_formula e1){
        final Lukasiewicz_disjunction_formula e = new Lukasiewicz_disjunction_formula(e0, e1, this);
        final Lukasiewicz_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukasiewicz_formula create_implication_formula(Lukasiewicz_formula e0, Lukasiewicz_formula e1){
        final Lukasiewicz_implication_formula e = new Lukasiewicz_implication_formula(e0, e1, this);
        final Lukasiewicz_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    private Map<String, Lukasiewicz_valuationVariable> valuationVariables = new TreeMap<String, Lukasiewicz_valuationVariable>();

    public Lukasiewicz_valuationVariable create_valuationVariable(String name){
        Lukasiewicz_valuationVariable v = valuationVariables.get(name);
        if(v == null){
            v = new Lukasiewicz_valuationVariable(name, this);
            valuationVariables.put(name, v);
        }
        return v;
    }

    private Map<Lukasiewicz_valuation, Lukasiewicz_valuation> valuations = new TreeMap<Lukasiewicz_valuation, Lukasiewicz_valuation>();

    private Map<String, Lukasiewicz_formulaVariable> formulaVariables = new TreeMap<String, Lukasiewicz_formulaVariable>();

    public Lukasiewicz_formulaVariable create_formulaVariable(String name){
        Lukasiewicz_formulaVariable v = formulaVariables.get(name);
        if(v == null){
            v = new Lukasiewicz_formulaVariable(name, this);
            formulaVariables.put(name, v);
        }
        return v;
    }

    private Map<Lukasiewicz_formula, Lukasiewicz_formula> formulas = new TreeMap<Lukasiewicz_formula, Lukasiewicz_formula>();

}
