/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukasiewicz.language.Lukasiewicz;

import mettel.core.tableau.MettelExpression;
public interface LukasiewiczExpression extends MettelExpression{

    int id();
    LukasiewiczObjectFactory factory();
    LukasiewiczExpression substitute(LukasiewiczSubstitution s);
    LukasiewiczExpression rewrite(LukasiewiczReplacement r);
    LukasiewiczSubstitution match(LukasiewiczExpression e);

    boolean match(LukasiewiczExpression e, LukasiewiczSubstitution s);
}
