/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavrona.language.Lukavrona;

import java.util.Map;
import java.util.TreeMap;

public class LukavronaDefaultObjectFactory implements LukavronaObjectFactory{

    private Map<LukavronaSubstitution, LukavronaSubstitution> subs = new TreeMap<LukavronaSubstitution, LukavronaSubstitution>();

    public LukavronaSubstitution getSubstitution(LukavronaSubstitution s){
        final LukavronaSubstitution old = subs.get(s);
        if(old == null){ 
            subs.put(s,s);
            return s;
        }else{ return old; }
    }

    private Map<LukavronaReplacement, LukavronaReplacement> reps = new TreeMap<LukavronaReplacement, LukavronaReplacement>();

    public LukavronaReplacement getReplacement(LukavronaReplacement r){
        final LukavronaReplacement old = reps.get(r);
        if(old == null){ 
            reps.put(r,r);
            return r;
        }else{ return old; }
    }

    public Lukavrona_valuation create_true_valuation(Lukavrona_formula e0){
        final Lukavrona_true_valuation e = new Lukavrona_true_valuation(e0, this);
        final Lukavrona_valuation old = valuations.get(e);
        if(old == null){ 
            valuations.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavrona_valuation create_false_valuation(Lukavrona_formula e0){
        final Lukavrona_false_valuation e = new Lukavrona_false_valuation(e0, this);
        final Lukavrona_valuation old = valuations.get(e);
        if(old == null){ 
            valuations.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavrona_formula create_negation_formula(Lukavrona_formula e0){
        final Lukavrona_negation_formula e = new Lukavrona_negation_formula(e0, this);
        final Lukavrona_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavrona_formula create_conjunction_formula(Lukavrona_formula e0, Lukavrona_formula e1){
        final Lukavrona_conjunction_formula e = new Lukavrona_conjunction_formula(e0, e1, this);
        final Lukavrona_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavrona_formula create_disjunction_formula(Lukavrona_formula e0, Lukavrona_formula e1){
        final Lukavrona_disjunction_formula e = new Lukavrona_disjunction_formula(e0, e1, this);
        final Lukavrona_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavrona_formula create_implication_formula(Lukavrona_formula e0, Lukavrona_formula e1){
        final Lukavrona_implication_formula e = new Lukavrona_implication_formula(e0, e1, this);
        final Lukavrona_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    private Map<String, Lukavrona_valuationVariable> valuationVariables = new TreeMap<String, Lukavrona_valuationVariable>();

    public Lukavrona_valuationVariable create_valuationVariable(String name){
        Lukavrona_valuationVariable v = valuationVariables.get(name);
        if(v == null){
            v = new Lukavrona_valuationVariable(name, this);
            valuationVariables.put(name, v);
        }
        return v;
    }

    private Map<Lukavrona_valuation, Lukavrona_valuation> valuations = new TreeMap<Lukavrona_valuation, Lukavrona_valuation>();

    private Map<String, Lukavrona_formulaVariable> formulaVariables = new TreeMap<String, Lukavrona_formulaVariable>();

    public Lukavrona_formulaVariable create_formulaVariable(String name){
        Lukavrona_formulaVariable v = formulaVariables.get(name);
        if(v == null){
            v = new Lukavrona_formulaVariable(name, this);
            formulaVariables.put(name, v);
        }
        return v;
    }

    private Map<Lukavrona_formula, Lukavrona_formula> formulas = new TreeMap<Lukavrona_formula, Lukavrona_formula>();

}
