/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavrona.language.Lukavrona;

public interface Lukavrona_formula extends LukavronaExpression{

    final int SORTID = 2;
}
