/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavrona.language.Lukavrona;

import mettel.core.tableau.MettelExpression;
public interface LukavronaExpression extends MettelExpression{

    int id();
    LukavronaObjectFactory factory();
    LukavronaExpression substitute(LukavronaSubstitution s);
    LukavronaExpression rewrite(LukavronaReplacement r);
    LukavronaSubstitution match(LukavronaExpression e);

    boolean match(LukavronaExpression e, LukavronaSubstitution s);
}
