/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavrona.language.Lukavrona;

import java.util.Set;
import mettel.core.tableau.MettelReplacement;

public interface LukavronaReplacement extends MettelReplacement{

    Lukavrona_valuation get_valuation(Lukavrona_valuation e);

    Set<Lukavrona_valuation> valuationKeys();

    boolean append(Lukavrona_valuation e0, Lukavrona_valuation e1);

    Lukavrona_formula get_formula(Lukavrona_formula e);

    Set<Lukavrona_formula> formulaKeys();

    boolean append(Lukavrona_formula e0, Lukavrona_formula e1);

    boolean append(LukavronaReplacement r);

}
