/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavrona.language.Lukavrona;

import mettel.core.tableau.MettelTableauObjectFactory;
import mettel.core.tableau.MettelReplacement;

public class LukavronaTableauObjectFactory implements MettelTableauObjectFactory{

    public MettelReplacement createReplacement(){
        return new LukavronaTreeReplacement();
    }

}
