/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavrona.language.Lukavrona;

public interface LukavronaObjectFactory{

    final LukavronaObjectFactory DEFAULT = new LukavronaDefaultObjectFactory();

    LukavronaReplacement getReplacement(LukavronaReplacement r);

    LukavronaSubstitution getSubstitution(LukavronaSubstitution s);

    Lukavrona_valuation create_true_valuation(Lukavrona_formula e0);    

    Lukavrona_valuation create_false_valuation(Lukavrona_formula e0);    

    Lukavrona_formula create_negation_formula(Lukavrona_formula e0);    

    Lukavrona_formula create_conjunction_formula(Lukavrona_formula e0, Lukavrona_formula e1);    

    Lukavrona_formula create_disjunction_formula(Lukavrona_formula e0, Lukavrona_formula e1);    

    Lukavrona_formula create_implication_formula(Lukavrona_formula e0, Lukavrona_formula e1);    

    Lukavrona_valuationVariable create_valuationVariable(String name);

    Lukavrona_formulaVariable create_formulaVariable(String name);

}
