/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavrona.language.Lukavrona;

abstract class LukavronaAbstractVariable extends LukavronaAbstractExpression implements LukavronaVariable{

    String name = null;

    public String name(){
        return name;
    }

    public LukavronaAbstractVariable(String name, LukavronaObjectFactory factory){
        super(factory);
        this.name = name;
    }

    public String toString(){
        return name;
    }
    int priority(){
        return -1;
    }
}
