/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavrona.language.Lukavrona;

public interface Lukavrona_valuation extends LukavronaExpression{

    final int SORTID = 1;
}
