/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavrona.language.Lukavrona;

import java.util.Comparator;

public class LukavronaIDComparator implements Comparator<LukavronaAbstractExpression>{

    public int compare(LukavronaAbstractExpression e0, LukavronaAbstractExpression e1){
        return e0.id() - e1.id();
    }

}
