/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb;

import mettel.core.tableau.MettelExpression;
public interface LukavronbExpression extends MettelExpression{

    int id();
    LukavronbObjectFactory factory();
    LukavronbExpression substitute(LukavronbSubstitution s);
    LukavronbExpression rewrite(LukavronbReplacement r);
    LukavronbSubstitution match(LukavronbExpression e);

    boolean match(LukavronbExpression e, LukavronbSubstitution s);
}
