/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb;

import java.util.Comparator;

public class LukavronbIDComparator implements Comparator<LukavronbAbstractExpression>{

    public int compare(LukavronbAbstractExpression e0, LukavronbAbstractExpression e1){
        return e0.id() - e1.id();
    }

}
