/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb;

import java.util.Map;
import java.util.TreeMap;

public class LukavronbDefaultObjectFactory implements LukavronbObjectFactory{

    private Map<LukavronbSubstitution, LukavronbSubstitution> subs = new TreeMap<LukavronbSubstitution, LukavronbSubstitution>();

    public LukavronbSubstitution getSubstitution(LukavronbSubstitution s){
        final LukavronbSubstitution old = subs.get(s);
        if(old == null){ 
            subs.put(s,s);
            return s;
        }else{ return old; }
    }

    private Map<LukavronbReplacement, LukavronbReplacement> reps = new TreeMap<LukavronbReplacement, LukavronbReplacement>();

    public LukavronbReplacement getReplacement(LukavronbReplacement r){
        final LukavronbReplacement old = reps.get(r);
        if(old == null){ 
            reps.put(r,r);
            return r;
        }else{ return old; }
    }

    public Lukavronb_valuation create_true_valuation(Lukavronb_formula e0){
        final Lukavronb_true_valuation e = new Lukavronb_true_valuation(e0, this);
        final Lukavronb_valuation old = valuations.get(e);
        if(old == null){ 
            valuations.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavronb_valuation create_false_valuation(Lukavronb_formula e0){
        final Lukavronb_false_valuation e = new Lukavronb_false_valuation(e0, this);
        final Lukavronb_valuation old = valuations.get(e);
        if(old == null){ 
            valuations.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavronb_formula create_negation_formula(Lukavronb_formula e0){
        final Lukavronb_negation_formula e = new Lukavronb_negation_formula(e0, this);
        final Lukavronb_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavronb_formula create_conjunction_formula(Lukavronb_formula e0, Lukavronb_formula e1){
        final Lukavronb_conjunction_formula e = new Lukavronb_conjunction_formula(e0, e1, this);
        final Lukavronb_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavronb_formula create_disjunction_formula(Lukavronb_formula e0, Lukavronb_formula e1){
        final Lukavronb_disjunction_formula e = new Lukavronb_disjunction_formula(e0, e1, this);
        final Lukavronb_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    public Lukavronb_formula create_implication_formula(Lukavronb_formula e0, Lukavronb_formula e1){
        final Lukavronb_implication_formula e = new Lukavronb_implication_formula(e0, e1, this);
        final Lukavronb_formula old = formulas.get(e);
        if(old == null){ 
            formulas.put(e,e);
            return e;
        }else{ return old; }
    }

    private Map<String, Lukavronb_valuationVariable> valuationVariables = new TreeMap<String, Lukavronb_valuationVariable>();

    public Lukavronb_valuationVariable create_valuationVariable(String name){
        Lukavronb_valuationVariable v = valuationVariables.get(name);
        if(v == null){
            v = new Lukavronb_valuationVariable(name, this);
            valuationVariables.put(name, v);
        }
        return v;
    }

    private Map<Lukavronb_valuation, Lukavronb_valuation> valuations = new TreeMap<Lukavronb_valuation, Lukavronb_valuation>();

    private Map<String, Lukavronb_formulaVariable> formulaVariables = new TreeMap<String, Lukavronb_formulaVariable>();

    public Lukavronb_formulaVariable create_formulaVariable(String name){
        Lukavronb_formulaVariable v = formulaVariables.get(name);
        if(v == null){
            v = new Lukavronb_formulaVariable(name, this);
            formulaVariables.put(name, v);
        }
        return v;
    }

    private Map<Lukavronb_formula, Lukavronb_formula> formulas = new TreeMap<Lukavronb_formula, Lukavronb_formula>();

}
