/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb;

import java.util.Map;
import mettel.core.tableau.MettelSubstitution;
public interface LukavronbSubstitution extends MettelSubstitution{

    Lukavronb_valuation get_valuation(Lukavronb_valuationVariable e);

    Map<Lukavronb_valuationVariable, Lukavronb_valuation> valuationMap();

    boolean append(Lukavronb_valuationVariable e0, Lukavronb_valuation e1);

    Lukavronb_formula get_formula(Lukavronb_formulaVariable e);

    Map<Lukavronb_formulaVariable, Lukavronb_formula> formulaMap();

    boolean append(Lukavronb_formulaVariable e0, Lukavronb_formula e1);

}
