/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb;

abstract class LukavronbAbstractVariable extends LukavronbAbstractExpression implements LukavronbVariable{

    String name = null;

    public String name(){
        return name;
    }

    public LukavronbAbstractVariable(String name, LukavronbObjectFactory factory){
        super(factory);
        this.name = name;
    }

    public String toString(){
        return name;
    }
    int priority(){
        return -1;
    }
}
