/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb;

public interface Lukavronb_formula extends LukavronbExpression{

    final int SORTID = 2;
}
