/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb;

import java.util.Comparator;

import mettel.core.tableau.MettelExpression;
import mettel.core.tableau.MettelSubstitution;
import mettel.core.tableau.MettelAbstractExpression;
abstract class LukavronbAbstractExpression extends MettelAbstractExpression implements LukavronbExpression{

    private static volatile int expressionCounter = 0;
    private int id = -1;
    protected LukavronbObjectFactory factory = null;

    LukavronbAbstractExpression(LukavronbObjectFactory factory){
        super();
        this.factory = factory;
        id = expressionCounter++;
    }

    LukavronbAbstractExpression(){
        this(LukavronbObjectFactory.DEFAULT);
    }

    public int id(){ return id; }

    public LukavronbObjectFactory factory(){ return factory; }

    abstract int sortId();

    abstract int priority();

    public MettelSubstitution match(MettelExpression e){
        if(e instanceof LukavronbExpression) return match((LukavronbExpression)e);
        return null;
    }

    public MettelExpression substitute(MettelSubstitution s){
        if(s instanceof LukavronbSubstitution) return substitute((LukavronbSubstitution)s);
        return null;
    }

    abstract int compareArgumentsTo(LukavronbAbstractExpression e, Comparator<LukavronbAbstractExpression> c);
    abstract int compareArguments(LukavronbAbstractExpression e, Comparator<LukavronbAbstractExpression> c);

}
