/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb;

import java.util.Comparator;

import mettel.core.tableau.MettelExpression;

public class Lukavronb_valuationVariable extends LukavronbAbstractVariable implements Lukavronb_valuation{

    public Lukavronb_valuationVariable(String name, LukavronbObjectFactory factory) {
        super(name, factory);
    }

    int sortId(){ return SORTID; }

    public LukavronbSubstitution match(LukavronbExpression e){
        LukavronbSubstitution s = new LukavronbTreeSubstitution();
        if(match(e,s)){
            return factory.getSubstitution(s);
        }else{ return null; }
    }

    public boolean match(LukavronbExpression e, LukavronbSubstitution s){
        if(!(e instanceof Lukavronb_valuation)){ return false; }
        return s.append(this,(Lukavronb_valuation)e);
    }

    public LukavronbExpression rewrite(LukavronbReplacement r) {
        Lukavronb_valuation e = r.get_valuation(this);
        return (e == null) ? this : e;
    }

    public LukavronbExpression substitute(LukavronbSubstitution s) {
        Lukavronb_valuation e = s.get_valuation(this);
        return (e == null) ? this : e;
    }

    private int hashCode = 0;
    public int hashCode(){
        if(hashCode == 0){
            hashCode = 23*SORTID + name.hashCode();
        }
        return hashCode;
    }

    public int compareTo(MettelExpression e){
        if(e instanceof Lukavronb_valuationVariable) return name.compareTo(((Lukavronb_valuationVariable)e).name());
        if(e instanceof Lukavronb_valuation) return -1;
        return SORTID - ((LukavronbAbstractExpression)e).sortId();
    }

    int compareArgumentsTo(LukavronbAbstractExpression e, Comparator<LukavronbAbstractExpression> c){return 0;}
    int compareArguments(LukavronbAbstractExpression e, Comparator<LukavronbAbstractExpression> c){return 0;}

    public boolean equals(Object o){
        if(o == this){ return true; }
        if(!(o instanceof Lukavronb_valuationVariable)){ return false; }
        return name.equals(((Lukavronb_valuationVariable)o).name());
    }

    public boolean isEquality(){
        return false;
    }
    public int length(){
        return 1;
    }
}
