/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb;

import mettel.core.tableau.MettelTableauObjectFactory;
import mettel.core.tableau.MettelReplacement;

public class LukavronbTableauObjectFactory implements MettelTableauObjectFactory{

    public MettelReplacement createReplacement(){
        return new LukavronbTreeReplacement();
    }

}
