/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb;

public interface LukavronbObjectFactory{

    final LukavronbObjectFactory DEFAULT = new LukavronbDefaultObjectFactory();

    LukavronbReplacement getReplacement(LukavronbReplacement r);

    LukavronbSubstitution getSubstitution(LukavronbSubstitution s);

    Lukavronb_valuation create_true_valuation(Lukavronb_formula e0);    

    Lukavronb_valuation create_false_valuation(Lukavronb_formula e0);    

    Lukavronb_formula create_negation_formula(Lukavronb_formula e0);    

    Lukavronb_formula create_conjunction_formula(Lukavronb_formula e0, Lukavronb_formula e1);    

    Lukavronb_formula create_disjunction_formula(Lukavronb_formula e0, Lukavronb_formula e1);    

    Lukavronb_formula create_implication_formula(Lukavronb_formula e0, Lukavronb_formula e1);    

    Lukavronb_valuationVariable create_valuationVariable(String name);

    Lukavronb_formulaVariable create_formulaVariable(String name);

}
