/**
 * This file is generated by MetTeL v2
 * which is designed and implemented
 * by Dmitry Tishkovsky.
 */
package Lukavronb.language.Lukavronb;

import java.util.Comparator;

import mettel.core.tableau.MettelExpression;

public class Lukavronb_disjunction_formula extends LukavronbAbstractExpression implements Lukavronb_formula{

    static final int PRIORITY = 5;
    private final int LENGTH;
    protected Lukavronb_formula e0 = null;
    protected Lukavronb_formula e1 = null;

    public Lukavronb_disjunction_formula(Lukavronb_formula e0, Lukavronb_formula e1, LukavronbObjectFactory f){
        super(f);
        int l = 1;
        this.e0 = e0;
        l += e0.length();
        this.e1 = e1;
        l += e1.length();
        LENGTH = l;
    }

    int sortId(){ return SORTID; }

    int priority(){ return PRIORITY; }

    public int length(){ return LENGTH; }

    public LukavronbSubstitution match(LukavronbExpression e){
        LukavronbSubstitution s = new LukavronbTreeSubstitution();
        if(match(e,s)){
            return factory.getSubstitution(s);
        }else{ return null; }
    }

    public boolean match(LukavronbExpression e, LukavronbSubstitution s){
        if(!(e instanceof Lukavronb_disjunction_formula)){ return false;}
        final Lukavronb_disjunction_formula ee = (Lukavronb_disjunction_formula)e;
        return e0.match(ee.e0, s) && e1.match(ee.e1, s);
    }

    public LukavronbExpression substitute(LukavronbSubstitution s){
        return factory.create_disjunction_formula((Lukavronb_formula)e0.substitute(s), (Lukavronb_formula)e1.substitute(s));
    }

    public LukavronbExpression rewrite(LukavronbReplacement s){
        LukavronbExpression e = s.get_formula(this);
        if(e != null){ return e; }
        final Lukavronb_formula ee = factory.create_disjunction_formula((Lukavronb_formula)e0.rewrite(s), (Lukavronb_formula)e1.rewrite(s));
        e = s.get_formula(ee);
        if(e == null){ return ee; }else{ return e; }
    }

    private int hashCode = 0;
    public int hashCode(){
        if(hashCode == 0){
            hashCode = 31*SORTID + PRIORITY;
            hashCode = 31*hashCode + e0.hashCode();
            hashCode = 31*hashCode + e1.hashCode();
        }
        return hashCode;
    }

    public boolean equals(Object o){
        if(o == this){ return true; }
        if(!(o instanceof Lukavronb_disjunction_formula)){ return false; }
        Lukavronb_disjunction_formula e = (Lukavronb_disjunction_formula) o;
        return (e0.equals(e.e0)) && (e1.equals(e.e1));
    }

    int compareArgumentsTo(LukavronbAbstractExpression e, Comparator<LukavronbAbstractExpression> c){
        int result = 0;
        result = c.compare((LukavronbAbstractExpression)e0, e);
        if(result >= 0){ return 1; }
        result = c.compare((LukavronbAbstractExpression)e1, e);
        if(result >= 0){ return 1; }
        return 0;
    }
    int compareArguments(LukavronbAbstractExpression e, Comparator<LukavronbAbstractExpression> c){
        final Lukavronb_disjunction_formula ee = (Lukavronb_disjunction_formula)e;
        int result = 0;
        result = c.compare((LukavronbAbstractExpression)e0, (LukavronbAbstractExpression)ee.e0);
        if(result != 0){ return result; }
        result = c.compare((LukavronbAbstractExpression)e1, (LukavronbAbstractExpression)ee.e1);
        if(result != 0){ return result; }
        return 0;
    }
    public int compareTo(MettelExpression e){
        if(e == this){ return 0; }
        if(!(e instanceof Lukavronb_formula)){ return SORTID - ((LukavronbAbstractExpression)e).sortId(); }
        if(e instanceof Lukavronb_formulaVariable){ return 1; }
        if(!(e instanceof Lukavronb_disjunction_formula)){ return PRIORITY - ((LukavronbAbstractExpression)e).priority(); }
        Lukavronb_disjunction_formula ee = (Lukavronb_disjunction_formula) e;
        int result = 0;
        result = e0.compareTo(ee.e0);
        if(result != 0){ return result; }
        result = e1.compareTo(ee.e1);
        if(result != 0){ return result; }
        return 0;
    }


    private String str = null;
    public String toString(){
        if(str == null){
            StringBuilder b = new StringBuilder();
            b.append('(');
            b.append(' ');
            b.append(e0);
            b.append(' ');
            b.append('|');
            b.append(' ');
            b.append(e1);
            b.append(' ');
            b.append(')');
            str = b.toString();
        }
        return str;
    }
}
